version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies.
      - npm install
      - echo Configuring enviroment variables
      - export NODE_ENV=production
      - echo Testing
      - npm test
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - package.json
    - package-lock.json
    - 'dist/**/*'
    - README.md