version: 0.2
phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - npm test
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - export NODE_ENV="production"
artifacts:
  type: zip
  files:
    - package.json
    - package-lock.json
    - 'dist/**/*'
    - README.md